# -*- coding: utf-8 -*-
"""PRODIGY_CS_02

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19LsTwbWZIKceyRFJLD5EKfxXyU2Cmd5K
"""

from PIL import Image

def encrypt_image(input_path, output_path, key):
    image = Image.open(input_path).convert('RGB')
    pixels = image.load()
    for i in range(image.size[0]):
        for j in range(image.size[1]):
            r, g, b = pixels[i, j]
            r_encrypted = (r + key) % 256
            g_encrypted = (g + key) % 256
            b_encrypted = (b ^ key) % 256
            pixels[i, j] = (r_encrypted, g_encrypted, b_encrypted)

    image.save(output_path)
    print(f"Encrypted image saved to {output_path}")

def decrypt_image(input_path, output_path, key):
    image = Image.open(input_path).convert('RGB')
    pixels = image.load()
    for i in range(image.size[0]):
        for j in range(image.size[1]):
            r, g, b = pixels[i, j]
            r_decrypted = (r - key) % 256
            g_decrypted = (g - key) % 256
            b_decrypted = (b ^ key) % 256
            pixels[i, j] = (r_decrypted, g_decrypted, b_decrypted)

    image.save(output_path)
    print(f"Decrypted image saved to {output_path}")


input_image_path = '/input_image_02.png'
encrypted_image_path = 'encrypted_image_02.png'
decrypted_image_path = 'decrypted_image_02.png'
encryption_key = 50

encrypt_image(input_image_path, encrypted_image_path, encryption_key)
decrypt_image(encrypted_image_path, decrypted_image_path, encryption_key)